### ISSUE TITLE
3.3.4 toggling DateTimePicker calendar causes page to break

### ISSUE THREAD

**Issue by idolize** [jquense/react-widgets#416] opened 2016-07-11 22:58 UTC
After updating to `3.3.4` I am seeing an issue when I click the little button on the right-hand side to open the calendar date selector (or time selector) in the `DateTimePicker` - it will navigate my browser back to the root URL whenever the button is clicked.

Maybe there is a missing `e.preventDefault()`?

The issue is not present in `3.3.3`

**Comment by vdh** [comment] 2016-07-12 06:23
It looks like the button component is missing a `type="button"`, and forms will treat a button without a type as a form submit button

**Comment by jquense** [comment] 2016-07-12 12:16
yup, small refactor regression. fixed in a bit

**Closed** 2016-07-12 12:22 UTC
