### ISSUE TITLE
Warning: setState(...): Can only update a mounted or mounting component

### ISSUE THREAD

**Issue by ArtanisAce** [jquense/react-widgets#428] opened 2016-07-25 14:17 UTC
Hi,

I've recently came across this warning in my application, when a popup window comes with a dropdown and a closing button, and while the dropdown is open you click to close the window:

`vendors.js:45195 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Popup component.`

it points to:

`safeSetState	@	Popup.js:251`
`    this.setState(nextState, this.setNextCallback(callback));`

`(anonymous function)	@	Popup.js:200`
`        return _this3.safeSetState({ status: CLOSED }, function () {`

`nextCallback	@	Popup.js:263`
`callback(event);`

This issue should have been fixed since release 3.2.0, but in my application is not working correctly... what can I do about this? Thanks!

**Comment by jquense** [comment] 2016-07-25 14:25
can you make sure that you actually have the latest version? sometimes stuff gets stuck in the cache or node_modules gets out of date despite it all

**Comment by ArtanisAce** [comment] 2016-07-25 14:42
Hi jquense,

Thanks for your quick answer! I have uninstalled the module and re-installed, and still the same problem... Should I try something else to make sure that nothing remains that might affect this? Thank you!

**Comment by ArtanisAce** [comment] 2016-07-28 12:48
Hi jquense,

you know what this might be? :(

**Comment by jquense** [comment] 2016-07-28 12:56
I have to take a look, looks like maybe a regression or bug

**Comment by ArtanisAce** [comment] 2016-07-28 16:04
@jquense thank you! Appreciate it :)

**Comment by SanjayHarkaj** [comment] 2016-08-30 12:57
Hi,
i have 3.3.1 version but still get the same error and MultiSelect in spite of new data and value doesn't update.
What to do???

**Comment by jquense** [comment] 2016-08-30 14:00
@SanjayHarkaj please upgrade to the latest version

**Comment by SanjayHarkaj** [comment] 2016-08-31 08:07
i have updated the latest version but still getting the same error.
Mulltiselect doesn't update i think its because of the error

> Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Popup component.
what should i do?
 thanks.

**Comment by jquense** [comment] 2016-08-31 09:24
the warning is just that a warning, so that wouldn't be the problem if something isn't updating. I suggest you open a new issue with a reproduction  if you have an issue with the multiselect

**Comment by SanjayHarkaj** [comment] 2016-08-31 09:47
okay thanks.

**Comment by jquense** [comment] 2016-09-02 12:38
i have this fixed in v4 i beleive

**Closed by jquense** 2016-09-02 12:38 UTC

**Comment by abbr** [comment] 2016-12-24 20:08
Since v4 is still on Beta, is there any chance to backport the fix to v3 or release v4 asap? Even though it's a warning, it easily leads to infinite loop and become a blocking issue. In my case, the warning points to this line in NumberPicker.js@3.4.4:

```
  handleMouseDown: function handleMouseDown(dir) {
    var method = dir === _constants.directions.UP ? this.increment : this.decrement;

->    this.setState({ active: dir });

    ...
```
