### ISSUE TITLE
Open datepicker by clicking on input area

### ISSUE THREAD

**Issue by countermeasure** [jquense/react-widgets#257] opened 2015-11-26 05:30 UTC
I'm trying to get a datepicker opening when a user clicks not just on the calendar icon, but anywhere in the text input area.

There doesn't seem to be an option for this, so I'm trying to implement a work around using DateTimePicker as a controlled component.

I'm using it with an `onClick` handler which, when called, sets the `open` property to `calendar`. That opens it just fine.

I can't get the widget to close once the user makes a selection though. I try to close the widget when a date has been selected by using the `onSelect` handler to set the `open` property to `false`. The problem is that after `onSelect` is called, `onClick` is called, and this opens the widget again.

Any thoughts on how I can get this working?

I'd like to do something like an `event.stopPropagation()` in the function called by `onSelect` to stop `onClick` being called after it, but I can't find a way to access the React event from `onSelect`.

**Comment by jquense** [comment] 2015-11-26 13:40
hi there, since the onClick is attached to the whole date picker any click will bubble up. What you want is to do in your onClick only toggle it to open when the event target is the input. 

you don't need to worry about closing it onSelect either that's the default behavior already, just make sure you are also providing an onToggle when are using the open prop, so you don't have to reimplement every open/close behavior.

**Comment by countermeasure** [comment] 2015-11-27 00:33
Thanks @jquense! That sorts it out.

For the benefit of anyone else who's trying to do this, include the `onClick` and `onToggle` attributes when you define your DateTimePicker:
```
<DateTimePicker
  ...
  all the other attributes
  ...
  onClick={this._handleInputClick}
  onToggle={this._handleToggle}
/>
```

Then add these functions to your component:
```
/**
 * Opens the widget when the user clicks in the input area.
 */
_handleInputClick: function(event) {
  if (event.target.tagName === 'INPUT') {
    this.setState({open: 'calendar'});
  }
},

/**
 * Toggles the widget between open and closed.
 */
_handleToggle: function() {
  var toggledState = (this.state.open) ? false : 'calendar';
  this.setState({open: toggledState});
},
```

**Closed** 2015-12-08 19:34 UTC

**Comment by slybridges** [comment] 2016-01-21 13:42
Thanks for the gist @countermeasure 

For reference, if using a DatePicker with Time, you'll have to modify the `_handleToggle` function like this to allow the TimePicker to open:

```javascript
  _handleToggle(view) {
    this.setState({ open: view })
  }
```

**Comment by ozluy** [comment] 2016-10-19 14:54
I have used this Component around 50 times on different pages is it possible for you to add this feature in new version of package?

**Comment by jquense** [comment] 2016-10-19 16:33
@ozluy maybe, i'm not sure that this behavior is a good default, or good UX. In any case if you are finding that you want this behavior all the time, then please wrap up the logic in a MyDatePicker component so you don't have to rewrite it every time you want it.

**Comment by ozluy** [comment] 2016-10-19 22:05
@jquense  I will push a pull request if you want later on?

**Comment by iangreenleaf** [comment] 2017-03-14 22:36
I put together a reusable wrapper component to do this that should handle all props being passed in, etc. Here's the code in the full ES6 glory:

```javascript
import React from 'react'
import { DateTimePicker } from 'react-widgets'

export default class Picker extends DateTimePicker {
  getInitialState(props) {
    return { open: (this.props.open ? this.props.open : false) }
  }

  render() {
    return (
      <DateTimePicker
        {...this.props}
        onClick={this._handleInputClick.bind(this, this.props.onClick)}
        onToggle={this._handleToggle.bind(this, this.props.onToggle)}
        open={this.state.open}
      />
    )
  }

  _handleInputClick(callback, event) {
    if (event.target.tagName === 'INPUT') {
      this._open(true)
    }
    return callback && callback(event)
  }

  _handleToggle(callback, view) {
    this._open(!this.state.open, view)
    return callback && callback()
  }

  _open(shouldOpen, view=null) {
    if (!view) {
      view = (this.props.time && !this.props.calendar) ? 'time' : 'calendar'
    }
    const toggledState = shouldOpen ? view : false
    this.setState({open: toggledState})
  }
}
```

**Comment by piotrkosytorz** [comment] 2017-04-03 15:53
@iangreenleaf God bless you!

**Comment by ersel** [comment] 2019-06-24 08:57
I had to make a few minor adjustments to @iangreenleaf 's code

```
// https://github.com/jquense/react-widgets/issues/257#issuecomment-286583288
import React from "react";
import { DateTimePicker } from "react-widgets";

class Picker extends DateTimePicker {
  constructor(props) {
    super(props);
    this.state = { open: props.open ? true : false };
  }

  render() {
    return (
      <DateTimePicker
        {...this.props}
        onClick={this._handleInputClick.bind(this, this.props.onClick)}
        onToggle={this._handleToggle.bind(this, this.props.onToggle)}
        open={this.state.open}
      />
    );
  }

  _handleInputClick(callback, event) {
    if (event.target.tagName === "INPUT") {
      this._open(true);
    }
    return callback && callback(event);
  }

  _handleToggle(callback, view) {
    this._open(!this.state.open, view);
    return callback && callback();
  }

  _open(shouldOpen, view = null) {
    if (!view) {
      view = this.props.time && !this.props.calendar ? "time" : "date";
    }
    const toggledState = shouldOpen ? view : false;
    this.setState({ open: toggledState });
  }
}

export default Picker;
```

**Comment by tailornirmal** [comment] 2019-06-27 14:33
@iangreenleaf I have multiple DateTimePicker in a single form. From referencing this i am able to achieve click on input but the problem is calendar is getting open for all date pickers.

`<DateTimePicker 
                  time={false}
                  onKeyDown={(e) => e.preventDefault() }
                  value={question.answers.length > 0 && question.answers[0] !== "" ? new Date(question.answers[0]) : null } 
                  onChange={value => this.handleChange(question, value)}
                  format="YYYY-MM-DD"
                  onClick={this.handleInputClick.bind(this, this.props.onClick)}
                  onToggle={this.handleToggle.bind(this, this.props.onToggle)}
                  open={open}`

I Have tried with add unique id to calendar using id property but open property takes only "calendar" not appended any value to it.

Can you please help me on this. Would be very helpful.

Thanks, 
Nick Taylor

**Comment by iangreenleaf** [comment] 2019-06-27 15:10
@tailornirmal sorry, I took a look and I'm not sure what the issue is for you. If you're having trouble with the plain component instead of my wrapper, you should try contacting the project maintainers and see if they can help.

**Comment by tailornirmal** [comment] 2019-06-27 15:13
@iangreenleaf Thanks Bud ! Yes you are right. its not a problem with wrapper. Probably would need to contact maintainers only in that case.

Many Thanks Again..
