### ISSUE TITLE
[v4] DateTimePicker can not change to Previous/Next month

### ISSUE THREAD

**Issue by olmobrutall** [jquense/react-widgets#593] opened 2017-06-22 14:53 UTC
Currently happening in two applications using `4.0.0-rc.10`

Thanks for the great work :)

**Comment by olmobrutall** [comment] 2017-06-26 10:34
Was a problem with currentDate / defaultCurrentDate... sorry.

**Comment by olmobrutall** [comment] 2017-06-26 12:33
Actually there is a problem in https://github.com/jquense/react-widgets/blob/v4/packages/react-widgets/src/DateTimePicker.js

* If you use `currentDate` then Previous/Next doesn't work.
* If you use `defaultCurrentDate` it works, but is ignored, creating precision problems when using DateTimePickers for date only.  

I think the `currentDate` should be in the list of `uncontrollable`:

```JS
export default uncontrollable(
  DateTimePicker,
  {
    open: 'onToggle',
    value: 'onChange',
    currentDate: 'onCurrentDateChange' //<--- Necessary
  },
  ['focus']
)
```

**Comment by jquense** [comment] 2017-06-26 13:13
can you post an example where it's not working?

**Comment by olmobrutall** [comment] 2017-06-26 13:42
The file where the problem happens is: 
https://github.com/signumsoftware/framework/blob/8e514e9834d9448d4dda6137e0af95244c52fe4d/Signum.React/Scripts/Lines/ValueLine.tsx#L495

And my hotfix, adding an intermediate state that emulates `uncontrollable` is here: 
https://github.com/signumsoftware/framework/blob/master/Signum.React/Scripts/Lines/ValueLine.tsx#L530

I know is not exactly an isolated example... 

What of the two cases you need an more explanation? 
* **If you use currentDate then Previous/Next doesn't work**:  I think this is by design. 
* **If you use defaultCurrentDate it works, but is ignored, creating precision problems when using DateTimePickers for date only**: This occurs because `currentDate` [is undefined](https://github.com/jquense/react-widgets/blob/v4/packages/react-widgets/src/DateTimePicker.js#L201 ) and then [`dates.merge` fallbacks to `new Date()`](https://github.com/jquense/react-widgets/blob/v4/packages/react-widgets/src/util/dates.js#L58) , adding the hours/minutes/milliseconds on the next date provided by `onChange`.

**Comment by jquense** [comment] 2017-06-29 13:11
ok definitely a bug. The problem is indeed that `defaultCurrentDate` is ignored I think I have an easy fix tho.

**Comment by jquense** [comment] 2017-07-25 14:12
should be fixed!

**Closed by jquense** 2017-07-25 14:12 UTC
Labels: bug
