### ISSUE TITLE
DateTimePicker icons offset in IE11

### ISSUE THREAD

**Issue by peterswallow** [jquense/react-widgets#867] opened 2018-10-22 14:19 UTC
Testing the DateTimePicker from your demo site (https://jquense.github.io/react-widgets/api/DateTimePicker/), shows that the Date and Time icons are slightly offset.

![image](https://user-images.githubusercontent.com/1467298/47297741-e8981500-d60d-11e8-94f1-43fae5277978.png)

It seems as though the `<button>` element has a top-offset of 13px, but I can't see where its coming from.

`<button tabindex="-1" title="Select date" class="rw-btn rw-btn-select" aria-label="Select date" type="button">
   <span class="rw-i rw-i-calendar" aria-hidden="true"></span>
</button>`

![image](https://user-images.githubusercontent.com/1467298/47297666-a5d63d00-d60d-11e8-8eaa-ed2a8ab1ee6f.png)

They display fine in Chrome, IE9 and IE10

**Comment by peterswallow** [comment] 2018-10-22 15:16
There is an `<input class="rw-widget-input rw-input">` element above these two buttons with this CSS class:

`.rw-widget0picker > * { height:100%}`

Removing this height attribute, seems to correct the position of the icon, but the textbox then becomes too small.

Is this the likely cause or a red-herring?

**Comment by peterswallow** [comment] 2018-10-23 08:32
Or removing `.rw-select > *` from `<button class="rw-btn rw-btn-select">` seems to fix it too.

It seems the height:100% is causing the issue, but not sure which element specifically to update

**Comment by Nowheresly** [comment] 2018-10-23 09:07
seems to be a duplicate of #685

**Comment by peterswallow** [comment] 2018-10-23 10:56
Yes! Thanks :)

**Closed** 2021-03-31 01:38 UTC
