### ISSUE TITLE
 Cannot read property 'matches' of null

### ISSUE THREAD

**Issue by vdh** [jquense/react-widgets#666] opened 2017-10-18 07:56 UTC
Due to the addition of `dom-helpers/query/matches` in [`src/utils/interaction.js`](https://github.com/jquense/react-widgets/commit/1d2419f0f1017c2df85ab6559ca46ef6a26de8ab#diff-44cea0b6ef4967bd773dfc2ab2b602a0R2) it's caused this race condition error:
```
Uncaught TypeError: Cannot read property 'matches' of null
```
Which appears to be this `dom-helpers` issue: https://github.com/react-bootstrap/dom-helpers/issues/29

**Comment by vdh** [comment] 2017-10-18 08:09
After further investigation, this also breaks the `Multiselect` component past `v4.0.0-rc.8` due to the import of `dom-helpers/src/query/closest`.

**Comment by jquense** [comment] 2017-10-18 12:10
Load your scripts below the the body not in the head :)

**Comment by vdh** [comment] 2017-10-19 02:10
@jquense So you're just going to bake this "asynchronous code dependencies implemented inside synchronous code dependencies" problem into the loading requirements of the entire `react-widgets` library? Is this requirement documented anywhere because it's alarming to suddenly find undocumented race conditions like this during loading.

This requirement will trickle on into forcing the _entire_ Webpack loader to be forced down below the body, which I can't do because I have a bunch of horrible legacy code that I need to inject localisation code for _ASAP_, before some cowboy coder's inline script tags start firing.

This kind of "undocumented dependencies that are just assumed to be there already immediately during first execution" coding style is _exactly_ what forced me to need to move all my script tags up to the top of the head in the first place!

**Comment by jquense** [comment] 2017-10-19 03:11
I understand you have issues here. I'm happy to take PRs. The problem is not async code nor a race condition.  it's that the document.body needs to exist in order to feature detect DOM functionality.

**Comment by vdh** [comment] 2017-10-20 05:30
@jquense But it _is_ asynchronous code, `DOMContentLoaded` is an event, and `document.body` is `null` before it fires.

[From Wikipedia:](https://en.wikipedia.org/wiki/Race_condition)
> A race condition or race hazard is the behavior of an electronic, software, or other system where the output is dependent on the sequence or timing of other uncontrollable events. It becomes a bug when events do not happen in the order the programmer intended.

I understand that it's best practises to put scripts below the body. If I _could_ do it, I would. I understand that most people probably don't encounter this issue, because they would be optimising their code and loading it after the body… but it's _absolutely_ a textbook definition of a race condition.

**Comment by vdh** [comment] 2017-10-20 06:03
@jquense PR created: https://github.com/react-bootstrap/dom-helpers/pull/33

**Comment by skulden13** [comment] 2017-12-14 12:13
Hi @jquense,

I noticed that you've approved the PR https://github.com/react-bootstrap/dom-helpers/pull/33 from @vdh. Thank you both!

Could you please also update the npm package in order to use the latest version of this package in react-widgets?

Thanks in advance, Denis

**Comment by seanpaulkelley** [comment] 2017-12-17 20:04
I am unable to use the current version of this package available via 
`yarn add react-widgets `
do to this issue's error.  From the comment by @skulden13 it looks like this is fixed in master branch.  I would love to try this fix out.  I am not entirely sure how to do this until package is updated.  

I am new to using package managers.  If I try to add this via 
`yarn add https://github.com/jquense/react-widgets.git`
I get error
Package "undefined@undefined" doesn't have a "name".

I posted a general question of use of package managers [here](https://stackoverflow.com/questions/47846321/adding-git-repository-with-yarn-results-in-error) because I am not sure if this is an issue with this repository or my use of yarn

**Closed** 2018-02-08 21:03 UTC

**Comment by skulden13** [comment] 2018-02-08 21:47
Hey @jquense,

I've noticed that you've updated dom-helpers and bump the version of react-widgets.
Thanks for your update! 🎉
