### ISSUE TITLE
DateTimePicker crashes Safari

### ISSUE THREAD

**Issue by jongbeau** [jquense/react-widgets#549] opened 2017-03-12 21:16 UTC
In Safari, load the documentation page and click on the Date`TimePicker` input. It crashes the browser. It works fine on Chrome and Firefox, however.

https://jquense.github.io/react-widgets/docs/#/datetime-picker?_k=sjwrwg

I repro'd this on Mac Safari 10.0.3 and iOS 10.2.1

**Comment by jquense** [comment] 2017-03-12 23:42
ugh safari is the worst...why is it even allowing that. Can you try with the v4 beta's and see if it still occurs

**Comment by kkamperschroer** [comment] 2017-03-13 02:39
Seeing this as well. @jquense do you have any more details on what Safari is doing? I'd be happy to attempt to get this fixed and issue a PR if it's not already resolved in v4 betas. Thanks!

**Comment by jquense** [comment] 2017-03-13 03:29
I don't have specific insight other than it seems to crash when you click the calendar button. generally js crashes are due to infinite loops but I have why I'd get one in safari but not others

**Comment by kkamperschroer** [comment] 2017-03-13 11:38
I just checked this morning and the issue is no longer present. Given that yesterday was the start of DST it seems that could potentially be related. Maybe some bad date processing somewhere in Safari related to that?

**Comment by jongbeau** [comment] 2017-03-13 15:09
you're right. l.o.l.

**Closed** 2017-04-24 18:59 UTC

**Comment by mkadin** [comment] 2021-03-15 01:59
This appears to be happening again today for me.  Seems worth fixing if its broken at least once per year!
